version: '3.5'

services:
  postgres:
    container_name: stk_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stkdb
      LC_ALL: C.UTF-8
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 2s
      retries: 20
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api:
    container_name: stk_api
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      PORT_API: 3000
      DB_PORT: 5432
      DB_ADDRESS: host.docker.internal
      DB_PASSWORD: 1234
      DB_USER: admin
      DB_NAME: stkdb
      JWT_SECRET: secret
      JWT_EXPIRES_IN: 10m
      JWT_REFRESH_TOKEN_SECRET: secret_refresh
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: 2 days
      ENVIRONMENT: local
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      s3server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "./local-launch/scripts/healthcheck.js", "http", "get", "host.docker.internal", "3000", "api/echo"]
      interval: 1s
      timeout: 2s
      retries: 20
    extra_hosts:
      - "host.docker.internal:host-gateway"
